on: 0.1
os: linux
files:
  - source: /
    destination: /home/ec2-user/Sources
permissions:
  - object: /home/ec2-user/Sources
    mode: 777
hooks:
  BeforeInstall:
    - location: scripts/start_server.sh
      runas: root
  AfterInstall:
    - location: scripts/restart_server.sh
      runas: root 
